dist: trusty
language: node_js
node_js:
  - "8.9"
addons:
  chrome: stable
before_script:
  - npm explore simulato-test-site -- nohup npm start &
script: 
  - npm run lint-ci
  - npm run generate-acceptance-tests
  - npm test