remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"
title: "Simulato"
title_seperator: "|"
feed: false
description: "Simulato is a tool that uses model based testing techniques to generate and run tests for web page user interfaces in the browser."
url: https://GannettDigital.github.io
# baseurl: /simulato
repository: "GannettDigital/simulato"
include: ["_pages"]
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      toc: true
      sidebar:
        nav: "docs"
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      sidebar:
        nav: "docs"